/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package nutricionistaVista.alimentos;

/**
 *
 * @author ferna
 */
public class alimentosAgregar extends javax.swing.JPanel {

    /**
     * Creates new form alimentosAgregar
     */
    public alimentosAgregar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTituloAlimento = new javax.swing.JLabel();
        jLTituloAgregarAlimentos = new javax.swing.JLabel();
        InputJTNombre = new javax.swing.JTextField();
        jLnombe1 = new javax.swing.JLabel();
        jLTipoDeComida = new javax.swing.JLabel();
        InputJTTipoDeComida = new javax.swing.JTextField();
        InputJTCalorias = new javax.swing.JTextField();
        jLCalorias = new javax.swing.JLabel();
        InputJTDetalle = new javax.swing.JTextField();
        jLDetalle = new javax.swing.JLabel();
        jLAptoParaVeg = new javax.swing.JLabel();
        InputCBAptoVegetarianos = new javax.swing.JCheckBox();
        InputCBLibreDeTacc = new javax.swing.JCheckBox();
        jLTacc = new javax.swing.JLabel();
        InputCBLacteo = new javax.swing.JCheckBox();
        jLLacteo = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setForeground(new java.awt.Color(0, 0, 255));

        jLTituloAlimento.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLTituloAlimento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTituloAlimento.setText("MENU DE ALIMENTOS");

        jLTituloAgregarAlimentos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLTituloAgregarAlimentos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTituloAgregarAlimentos.setText("AGREGAR ");

        jLnombe1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLnombe1.setText("Nombre:");

        jLTipoDeComida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLTipoDeComida.setText("Tipo de Comida:");

        jLCalorias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLCalorias.setText("Calorias por 100g:");

        jLDetalle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLDetalle.setText("Detalle:");

        jLAptoParaVeg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLAptoParaVeg.setText("Apto para Vegetarianos:");

        InputCBAptoVegetarianos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputCBAptoVegetarianosActionPerformed(evt);
            }
        });

        jLTacc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLTacc.setText("Libre de TACC:");

        jLLacteo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLLacteo.setText("Lacteo:");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLnombe1)
                            .addComponent(jLTipoDeComida)
                            .addComponent(jLCalorias)
                            .addComponent(jLDetalle))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(InputJTDetalle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(InputJTNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                .addComponent(InputJTTipoDeComida)
                                .addComponent(InputJTCalorias))))
                    .addComponent(jLTituloAgregarAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLTacc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(InputCBLibreDeTacc))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLAptoParaVeg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(InputCBAptoVegetarianos))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLLacteo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(InputCBLacteo)))
                        .addGap(9, 9, 9)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTituloAlimento, javax.swing.GroupLayout.DEFAULT_SIZE, 1063, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLTituloAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLTituloAgregarAlimentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnombe1)
                    .addComponent(InputJTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTipoDeComida)
                    .addComponent(InputJTTipoDeComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCalorias)
                    .addComponent(InputJTCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDetalle)
                    .addComponent(InputJTDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InputCBAptoVegetarianos, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLAptoParaVeg, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(InputCBLibreDeTacc)
                    .addComponent(jLTacc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InputCBLacteo)
                    .addComponent(jLLacteo))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void InputCBAptoVegetarianosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputCBAptoVegetarianosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputCBAptoVegetarianosActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox InputCBAptoVegetarianos;
    private javax.swing.JCheckBox InputCBLacteo;
    private javax.swing.JCheckBox InputCBLibreDeTacc;
    private javax.swing.JTextField InputJTCalorias;
    private javax.swing.JTextField InputJTDetalle;
    private javax.swing.JTextField InputJTNombre;
    private javax.swing.JTextField InputJTTipoDeComida;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLAptoParaVeg;
    private javax.swing.JLabel jLCalorias;
    private javax.swing.JLabel jLDetalle;
    private javax.swing.JLabel jLLacteo;
    private javax.swing.JLabel jLTacc;
    private javax.swing.JLabel jLTipoDeComida;
    private javax.swing.JLabel jLTituloAgregarAlimentos;
    private javax.swing.JLabel jLTituloAlimento;
    private javax.swing.JLabel jLnombe1;
    // End of variables declaration//GEN-END:variables
}
