/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package nutricionistaVista.alimentos;

/**
 *
 * @author ferna
 */
public class alimentosBuscar extends javax.swing.JPanel {

    /**
     * Creates new form alimentosBuscar
     */
    public alimentosBuscar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTituloAlimento = new javax.swing.JLabel();
        jLTituloAgregarAlimentos1 = new javax.swing.JLabel();
        jCBSeleccionarAlimento = new javax.swing.JComboBox<>();
        jLSeleccionarAlimento = new javax.swing.JLabel();
        jLNombre2 = new javax.swing.JLabel();
        OutputJTNombre5 = new javax.swing.JTextField();
        jLTipoComida2 = new javax.swing.JLabel();
        OutputJTTipoDeComida5 = new javax.swing.JTextField();
        OutputJTCalorias5 = new javax.swing.JTextField();
        jLCalorias2 = new javax.swing.JLabel();
        OutputJTDetalle5 = new javax.swing.JTextField();
        jLDetalle2 = new javax.swing.JLabel();
        jLAptoParaVegetariano2 = new javax.swing.JLabel();
        OutputCBAptoVegetariano5 = new javax.swing.JCheckBox();
        OutputCBLibreDeTacc5 = new javax.swing.JCheckBox();
        jLTacc2 = new javax.swing.JLabel();
        OutputCBLacteo5 = new javax.swing.JCheckBox();
        jLLacteo2 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();

        jLTituloAlimento.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLTituloAlimento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTituloAlimento.setText("MENU DE ALIMENTOS");

        jLTituloAgregarAlimentos1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLTituloAgregarAlimentos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTituloAgregarAlimentos1.setText("BUSCAR");

        jCBSeleccionarAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBSeleccionarAlimentoActionPerformed(evt);
            }
        });

        jLSeleccionarAlimento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLSeleccionarAlimento.setText("Seleccionar Alimento: ");

        jLNombre2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLNombre2.setText("Nombre:");

        jLTipoComida2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLTipoComida2.setText("Tipo de Comida:");

        jLCalorias2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLCalorias2.setText("Calorias por 100g:");

        jLDetalle2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLDetalle2.setText("Detalle:");

        jLAptoParaVegetariano2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLAptoParaVegetariano2.setText("Apto para Vegetarianos:");

        jLTacc2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLTacc2.setText("Libre de TACC:");

        jLLacteo2.setText("Lacteo:");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLTituloAlimento, javax.swing.GroupLayout.DEFAULT_SIZE, 1075, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(379, 379, 379)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLTituloAgregarAlimentos1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLSeleccionarAlimento)
                                    .addComponent(jLNombre2)
                                    .addComponent(jLTipoComida2)
                                    .addComponent(jLCalorias2)
                                    .addComponent(jLDetalle2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(OutputJTNombre5)
                                    .addComponent(jCBSeleccionarAlimento, 0, 193, Short.MAX_VALUE)
                                    .addComponent(OutputJTTipoDeComida5)
                                    .addComponent(OutputJTCalorias5)
                                    .addComponent(OutputJTDetalle5)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLTacc2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(OutputCBLibreDeTacc5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLAptoParaVegetariano2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(OutputCBAptoVegetariano5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLLacteo2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(OutputCBLacteo5)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(459, 459, 459))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTituloAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLTituloAgregarAlimentos1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSeleccionarAlimento)
                    .addComponent(jCBSeleccionarAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombre2)
                    .addComponent(OutputJTNombre5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTipoComida2)
                    .addComponent(OutputJTTipoDeComida5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OutputJTCalorias5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCalorias2))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDetalle2)
                    .addComponent(OutputJTDetalle5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OutputCBAptoVegetariano5)
                    .addComponent(jLAptoParaVegetariano2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(OutputCBLibreDeTacc5)
                    .addComponent(jLTacc2))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(OutputCBLacteo5)
                    .addComponent(jLLacteo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCBSeleccionarAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBSeleccionarAlimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBSeleccionarAlimentoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox OutputCBAptoVegetariano5;
    private javax.swing.JCheckBox OutputCBLacteo5;
    private javax.swing.JCheckBox OutputCBLibreDeTacc5;
    private javax.swing.JTextField OutputJTCalorias5;
    private javax.swing.JTextField OutputJTDetalle5;
    private javax.swing.JTextField OutputJTNombre5;
    private javax.swing.JTextField OutputJTTipoDeComida5;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> jCBSeleccionarAlimento;
    private javax.swing.JLabel jLAptoParaVegetariano2;
    private javax.swing.JLabel jLCalorias2;
    private javax.swing.JLabel jLDetalle2;
    private javax.swing.JLabel jLLacteo2;
    private javax.swing.JLabel jLNombre2;
    private javax.swing.JLabel jLSeleccionarAlimento;
    private javax.swing.JLabel jLTacc2;
    private javax.swing.JLabel jLTipoComida2;
    private javax.swing.JLabel jLTituloAgregarAlimentos1;
    private javax.swing.JLabel jLTituloAlimento;
    // End of variables declaration//GEN-END:variables
}
