/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package nutricionistaVista.alimentos;

import conexion.alimentoData;
import entidades.alimento;
import java.awt.Graphics;
import java.awt.Image;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author ferna
 */
public class alimentosBuscar extends javax.swing.JPanel {

 private List<alimento> alimentos;
   
    public alimentosBuscar() {
        initComponents();
        cargarCombo();
        
          jCBSeleccionarAlimento.addActionListener(evt -> {
            String nombreSel = (String) jCBSeleccionarAlimento.getSelectedItem();
            if (nombreSel == null) return;

            // Buscamos en la lista el objeto alimento con ese nombre
            for (alimento a : alimentos) {
                if (a.getNombre().equals(nombreSel)) {
                    OutputJTNombre5.setText(a.getNombre());
                    
                    //Botones
                    
                    //Seteamos
                    
                    rbDesayuno.setSelected(false);
                    rbAlmuerzo.setSelected(false);
                    rbMerienda.setSelected(false);
                    rbCena.setSelected(false);
                    rbColacion.setSelected(false);
                    
                    if (a.getCategoria().equalsIgnoreCase("d")){
                    rbDesayuno.setSelected(true);
                    } else if (a.getCategoria().equalsIgnoreCase("a")){
                    rbAlmuerzo.setSelected(true);
                    } else if (a.getCategoria().equalsIgnoreCase("m")){
                    rbMerienda.setSelected(true);
                    } else if (a.getCategoria().equalsIgnoreCase("c")){
                    rbCena.setSelected(true);
                    } else if (a.getCategoria().equalsIgnoreCase("co"))
                        rbColacion.setSelected(true);
                    OutputJTCalorias5.setText(String.valueOf(a.getCalorias()));
                    OutputCBAptoVegetariano5.setSelected(a.isAptoCeliacos());
                    OutputCBLacteo5.setSelected(a.isBajoLactosa());
                    break;
                }
            }
        });
    }
    private void cargarCombo() {
        alimentoData ad = new alimentoData();
        alimentos = ad.listarAlimentos();
        DefaultComboBoxModel<String> m = new DefaultComboBoxModel<>();
        for (alimento a : alimentos) {
            m.addElement(a.getNombre());
        }
        jCBSeleccionarAlimento.setModel(m);
        jCBSeleccionarAlimento.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTituloAgregarAlimentos1 = new javax.swing.JLabel();
        jCBSeleccionarAlimento = new javax.swing.JComboBox<>();
        jLSeleccionarAlimento = new javax.swing.JLabel();
        jLNombre2 = new javax.swing.JLabel();
        OutputJTNombre5 = new javax.swing.JTextField();
        jLTipoComida2 = new javax.swing.JLabel();
        OutputJTCalorias5 = new javax.swing.JTextField();
        jLCalorias2 = new javax.swing.JLabel();
        jLAptoParaVegetariano2 = new javax.swing.JLabel();
        OutputCBAptoVegetariano5 = new javax.swing.JCheckBox();
        OutputCBLacteo5 = new javax.swing.JCheckBox();
        jLLacteo2 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rbDesayuno = new javax.swing.JCheckBox();
        rbAlmuerzo = new javax.swing.JCheckBox();
        rbMerienda = new javax.swing.JCheckBox();
        rbCena = new javax.swing.JCheckBox();
        rbColacion = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(204, 255, 255));

        jLTituloAgregarAlimentos1.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLTituloAgregarAlimentos1.setForeground(new java.awt.Color(0, 0, 0));
        jLTituloAgregarAlimentos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTituloAgregarAlimentos1.setText("BUSCAR");

        jCBSeleccionarAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBSeleccionarAlimentoActionPerformed(evt);
            }
        });

        jLSeleccionarAlimento.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLSeleccionarAlimento.setForeground(new java.awt.Color(0, 0, 0));
        jLSeleccionarAlimento.setText("Seleccionar Alimento: ");

        jLNombre2.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLNombre2.setForeground(new java.awt.Color(0, 0, 0));
        jLNombre2.setText("Nombre:");

        jLTipoComida2.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLTipoComida2.setForeground(new java.awt.Color(0, 0, 0));
        jLTipoComida2.setText("Tipo de Comida:");

        jLCalorias2.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLCalorias2.setForeground(new java.awt.Color(0, 0, 0));
        jLCalorias2.setText("Calorias por 100g:");

        jLAptoParaVegetariano2.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLAptoParaVegetariano2.setForeground(new java.awt.Color(0, 0, 0));
        jLAptoParaVegetariano2.setText("Apto para Vegetarianos:");

        jLLacteo2.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLLacteo2.setForeground(new java.awt.Color(0, 0, 0));
        jLLacteo2.setText("Lacteo:");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        rbDesayuno.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        rbDesayuno.setForeground(new java.awt.Color(0, 0, 0));
        rbDesayuno.setText("Desayuno");

        rbAlmuerzo.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        rbAlmuerzo.setForeground(new java.awt.Color(0, 0, 0));
        rbAlmuerzo.setText("Almuerzo");

        rbMerienda.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        rbMerienda.setForeground(new java.awt.Color(0, 0, 0));
        rbMerienda.setText("Merienda");

        rbCena.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        rbCena.setForeground(new java.awt.Color(0, 0, 0));
        rbCena.setText("Cena");

        rbColacion.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        rbColacion.setForeground(new java.awt.Color(0, 0, 0));
        rbColacion.setText("Colacion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbAlmuerzo)
                    .addComponent(rbMerienda)
                    .addComponent(rbDesayuno))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbCena)
                    .addComponent(rbColacion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbDesayuno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbAlmuerzo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(rbMerienda))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(rbCena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbColacion)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(379, 379, 379)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLSeleccionarAlimento)
                            .addComponent(jLNombre2)
                            .addComponent(jLTipoComida2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(OutputJTNombre5)
                                .addComponent(jCBSeleccionarAlimento, 0, 193, Short.MAX_VALUE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jLTituloAgregarAlimentos1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLAptoParaVegetariano2)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(jLCalorias2)))
                            .addComponent(jLLacteo2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OutputJTCalorias5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OutputCBAptoVegetariano5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(OutputCBLacteo5)
                                .addGap(92, 92, 92)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTituloAgregarAlimentos1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSeleccionarAlimento)
                    .addComponent(jCBSeleccionarAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombre2)
                    .addComponent(OutputJTNombre5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLTipoComida2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCalorias2)
                    .addComponent(OutputJTCalorias5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OutputCBAptoVegetariano5)
                    .addComponent(jLAptoParaVegetariano2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OutputCBLacteo5)
                    .addComponent(jLLacteo2)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCBSeleccionarAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBSeleccionarAlimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBSeleccionarAlimentoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
            OutputJTNombre5.setText("");
              //Botones
        rbDesayuno.setSelected(false);
        rbAlmuerzo.setSelected(false);
        rbMerienda.setSelected(false);
        rbCena.setSelected(false);
        rbColacion.setSelected(false);
        //Botones
            OutputJTCalorias5.setText("");
            OutputCBAptoVegetariano5.setSelected(false);
            OutputCBLacteo5.setSelected(false);
            jCBSeleccionarAlimento.setSelectedIndex(-1);
            OutputJTNombre5.requestFocusInWindow();
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox OutputCBAptoVegetariano5;
    private javax.swing.JCheckBox OutputCBLacteo5;
    private javax.swing.JTextField OutputJTCalorias5;
    private javax.swing.JTextField OutputJTNombre5;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> jCBSeleccionarAlimento;
    private javax.swing.JLabel jLAptoParaVegetariano2;
    private javax.swing.JLabel jLCalorias2;
    private javax.swing.JLabel jLLacteo2;
    private javax.swing.JLabel jLNombre2;
    private javax.swing.JLabel jLSeleccionarAlimento;
    private javax.swing.JLabel jLTipoComida2;
    private javax.swing.JLabel jLTituloAgregarAlimentos1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox rbAlmuerzo;
    private javax.swing.JCheckBox rbCena;
    private javax.swing.JCheckBox rbColacion;
    private javax.swing.JCheckBox rbDesayuno;
    private javax.swing.JCheckBox rbMerienda;
    // End of variables declaration//GEN-END:variables


}
