/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package nutricionistaVista.paciente;

import conexion.pacienteData;
import entidades.paciente;
import java.util.List;
import javax.swing.JComboBox;

/**
 *
 * @author ferna
 */
public class pacienteModificar extends javax.swing.JPanel {

   private JComboBox<String> comboPacientes;
   private List<paciente> listaPacientes;
   private pacienteData pacienteData;
   
    public pacienteModificar() {
        initComponents();
        pacienteData = new pacienteData();
        cargarPacientes();
        
        //Evitar modificacion de los Botones
        rbHombre.setEnabled(false);
        rbMujer.setEnabled(false);
        rbCeliaquia.setEnabled(false);
        rbVegetariano.setEnabled(false);
        rbIntoleranteLactosa.setEnabled(false);
        rbSubirPeso.setEnabled(false);
        rbBajarPeso.setEnabled(false);
        rbMantenerPeso.setEnabled(false);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEliminarPaciente = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboBoxPacientes = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        outputPesoPaciente = new javax.swing.JTextField();
        outputEdadPaciente = new javax.swing.JTextField();
        outputAlturaPaciente = new javax.swing.JTextField();
        btnActualizarPaciente = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rbCeliaquia = new javax.swing.JRadioButton();
        rbVegetariano = new javax.swing.JRadioButton();
        rbIntoleranteLactosa = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        rbMujer = new javax.swing.JRadioButton();
        rbHombre = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        rbSubirPeso = new javax.swing.JRadioButton();
        rbBajarPeso = new javax.swing.JRadioButton();
        rbMantenerPeso = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 800));

        jPanelEliminarPaciente.setBackground(new java.awt.Color(0, 102, 102));
        jPanelEliminarPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Seleccionar Paciente:");

        comboBoxPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxPacientesActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Peso Paciente:");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Edad:");

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Sexo:");

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Objetivo:");

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Condicion especial:");

        outputPesoPaciente.setEditable(false);
        outputPesoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputPesoPacienteActionPerformed(evt);
            }
        });

        outputEdadPaciente.setEditable(false);
        outputEdadPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputEdadPacienteActionPerformed(evt);
            }
        });

        outputAlturaPaciente.setEditable(false);

        btnActualizarPaciente.setText("GUARDAR");
        btnActualizarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPacienteActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Altura");

        jButton1.setText("MODIFICAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        rbCeliaquia.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        rbCeliaquia.setForeground(new java.awt.Color(0, 0, 0));
        rbCeliaquia.setText("Celiaquia");
        rbCeliaquia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCeliaquiaActionPerformed(evt);
            }
        });

        rbVegetariano.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        rbVegetariano.setForeground(new java.awt.Color(0, 0, 0));
        rbVegetariano.setText("Vegetariano");

        rbIntoleranteLactosa.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        rbIntoleranteLactosa.setForeground(new java.awt.Color(0, 0, 0));
        rbIntoleranteLactosa.setText("Intolerancia a la lactosa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbCeliaquia)
                    .addComponent(rbVegetariano)
                    .addComponent(rbIntoleranteLactosa))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rbCeliaquia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbVegetariano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbIntoleranteLactosa)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        rbMujer.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        rbMujer.setForeground(new java.awt.Color(0, 0, 0));
        rbMujer.setText("Mujer");

        rbHombre.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        rbHombre.setForeground(new java.awt.Color(0, 0, 0));
        rbHombre.setText("Hombre");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbMujer)
                    .addComponent(rbHombre))
                .addGap(0, 26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(rbHombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbMujer))
        );

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        rbSubirPeso.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        rbSubirPeso.setForeground(new java.awt.Color(0, 0, 0));
        rbSubirPeso.setText("Subir de peso");

        rbBajarPeso.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        rbBajarPeso.setForeground(new java.awt.Color(0, 0, 0));
        rbBajarPeso.setText("Bajar de peso");

        rbMantenerPeso.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        rbMantenerPeso.setForeground(new java.awt.Color(0, 0, 0));
        rbMantenerPeso.setText("Mantener Peso");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(rbSubirPeso))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbBajarPeso)
                            .addComponent(rbMantenerPeso))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbSubirPeso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(rbMantenerPeso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbBajarPeso)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelEliminarPacienteLayout = new javax.swing.GroupLayout(jPanelEliminarPaciente);
        jPanelEliminarPaciente.setLayout(jPanelEliminarPacienteLayout);
        jPanelEliminarPacienteLayout.setHorizontalGroup(
            jPanelEliminarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEliminarPacienteLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(jPanelEliminarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEliminarPacienteLayout.createSequentialGroup()
                        .addGroup(jPanelEliminarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEliminarPacienteLayout.createSequentialGroup()
                                .addGroup(jPanelEliminarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(jPanelEliminarPacienteLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabel10)
                                .addGap(69, 69, 69)))
                        .addGroup(jPanelEliminarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outputAlturaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outputEdadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelEliminarPacienteLayout.createSequentialGroup()
                                .addComponent(outputPesoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel7)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelEliminarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelEliminarPacienteLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEliminarPacienteLayout.createSequentialGroup()
                        .addGroup(jPanelEliminarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelEliminarPacienteLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanelEliminarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEliminarPacienteLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11))
                            .addGroup(jPanelEliminarPacienteLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(btnActualizarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanelEliminarPacienteLayout.setVerticalGroup(
            jPanelEliminarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEliminarPacienteLayout.createSequentialGroup()
                .addGroup(jPanelEliminarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEliminarPacienteLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEliminarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(outputEdadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanelEliminarPacienteLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanelEliminarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(comboBoxPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)
                        .addGroup(jPanelEliminarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(outputPesoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanelEliminarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEliminarPacienteLayout.createSequentialGroup()
                        .addGroup(jPanelEliminarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEliminarPacienteLayout.createSequentialGroup()
                                .addGroup(jPanelEliminarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelEliminarPacienteLayout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelEliminarPacienteLayout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(jLabel11)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEliminarPacienteLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(outputAlturaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42)
                        .addGroup(jPanelEliminarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActualizarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(242, 242, 242))
                    .addGroup(jPanelEliminarPacienteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanelEliminarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanelEliminarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(308, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rbCeliaquiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCeliaquiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCeliaquiaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // BOTON PARA MODIFICAR PACIENTES
        outputPesoPaciente.setEditable(true);
        outputEdadPaciente.setEditable(true);
        outputAlturaPaciente.setEditable(true);
        rbHombre.setEnabled(true);
        rbMujer.setEnabled(true);
        rbCeliaquia.setEnabled(true);
        rbVegetariano.setEnabled(true);
        rbIntoleranteLactosa.setEnabled(true);
        rbSubirPeso.setEnabled(true);
        rbBajarPeso.setEnabled(true);
        rbMantenerPeso.setEnabled(true);
        
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnActualizarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPacienteActionPerformed

      //BOTON PARA ACTUALIZAR EL PACIENTE
      int index = comboBoxPacientes.getSelectedIndex();
      if (index >= 0 && index < listaPacientes.size()) {
          //Se obtiene el index (Id)
            paciente p = listaPacientes.get(index);
          //Variables y atributos
        int id = listaPacientes.get(index).getIdPaciente();
        String nombre = p.getNombre();
        String apellido = p.getApellido();
        double peso = Double.parseDouble(outputPesoPaciente.getText());
        int edad = Integer.parseInt(outputEdadPaciente.getText());
        double altura = Double.parseDouble(outputAlturaPaciente.getText());
        String sexo = "";
        
        //Definir el sexo
        if (rbHombre.isSelected()){
        sexo = "hombre";
        } else if (rbMujer.isSelected()){
        sexo = "mujer";
        } else {
            System.out.println("Error en seleccionar sexo");
        }
        
        //Definir El objetivo
        
        String objetivo = "";
        
        if (rbSubirPeso.isSelected()){
        objetivo = "subir";
        } else if (rbBajarPeso.isSelected()){
        objetivo = "bajar";
        } else if (rbMantenerPeso.isSelected()){
        objetivo = "mantener";
        }
        
        boolean vegetariano = rbVegetariano.isSelected();
        boolean celiaco = rbCeliaquia.isSelected();
        boolean intoleranteLactosa = rbIntoleranteLactosa.isSelected();
          
          //Variables y atributos

          //Crear objeto Paciente
            paciente pacienteActualizado = new paciente(id, nombre, apellido, edad, peso, altura, sexo, objetivo, vegetariano, celiaco, intoleranteLactosa);
          

          //Conexion a paciente data
           pacienteData pac = new pacienteData();
          
          //Funcion y resultado
          boolean resultado = pac.actualizarPaciente(pacienteActualizado);
          
          if (resultado == true){
              System.out.println("Exito");
          } else {
              System.out.println("Hubo un error.");
          }
          
        }
    }//GEN-LAST:event_btnActualizarPacienteActionPerformed

    private void outputEdadPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputEdadPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputEdadPacienteActionPerformed

    private void outputPesoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputPesoPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputPesoPacienteActionPerformed

    private void comboBoxPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxPacientesActionPerformed
        actualizarDetallesPaciente();
    }//GEN-LAST:event_comboBoxPacientesActionPerformed

    
    //Funcion para cargar pacientes al comboBox
    private void cargarPacientes() {
    listaPacientes = pacienteData.obtenerPacientes();
    //Se limpia el comboBox
    comboBoxPacientes.removeAllItems();
    
    //For each para recorrer todo
    for (paciente p : listaPacientes){
    comboBoxPacientes.addItem(p.getNombre() + " " +p.getApellido());
    }
    }
    
    private void actualizarDetallesPaciente() {
    
    int index = comboBoxPacientes.getSelectedIndex();
        
        if (index >= 0 && index < listaPacientes.size()) {
            paciente p = listaPacientes.get(index);
            
            outputEdadPaciente.setText(String.valueOf(p.getEdad()));
            outputPesoPaciente.setText(String.valueOf(p.getPeso()));
            outputAlturaPaciente.setText(String.valueOf((float) p.getAltura()));
            
            // Configurar el sexo en los radio buttons
            rbHombre.setSelected(false);
            rbMujer.setSelected(false);
 
            if ("hombre".equals(p.getSexo())) {
                rbHombre.setSelected(true);
            } else if ("mujer".equals(p.getSexo())) {
                rbMujer.setSelected(true);
            }
            
            //Ajuste para solucionar problemas con la toma de dato
            System.out.println("Objetivo del paciente actual: ");
            System.out.println(p.getObjetivo());
            
            //Setear datos
            rbSubirPeso.setSelected(false);
            rbBajarPeso.setSelected(false);
            rbMantenerPeso.setSelected(false);
            
            
            if ("subir".equalsIgnoreCase(p.getObjetivo())){
            rbSubirPeso.setSelected(true);
            } else if ("bajar".equalsIgnoreCase(p.getObjetivo())){
            rbBajarPeso.setSelected(true);
            } else if ("mantener".equalsIgnoreCase(p.getObjetivo())){
            rbMantenerPeso.setSelected(true);
            }
            
            
            
            // Configurar condiciones especiales
            rbCeliaquia.setSelected(p.isCeliaco());
            rbVegetariano.setSelected(p.isVegetariano());
            rbIntoleranteLactosa.setSelected(p.isIntoleranteLactosa());
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarPaciente;
    private javax.swing.JComboBox<String> comboBoxPacientes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelEliminarPaciente;
    private javax.swing.JTextField outputAlturaPaciente;
    private javax.swing.JTextField outputEdadPaciente;
    private javax.swing.JTextField outputPesoPaciente;
    private javax.swing.JRadioButton rbBajarPeso;
    private javax.swing.JRadioButton rbCeliaquia;
    private javax.swing.JRadioButton rbHombre;
    private javax.swing.JRadioButton rbIntoleranteLactosa;
    private javax.swing.JRadioButton rbMantenerPeso;
    private javax.swing.JRadioButton rbMujer;
    private javax.swing.JRadioButton rbSubirPeso;
    private javax.swing.JRadioButton rbVegetariano;
    // End of variables declaration//GEN-END:variables
}
