/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package nutricionistaVista.dietas;



/**
 *
 * @author ferna
 */
public class dietasConsultarDieta extends javax.swing.JPanel {

    /**
     * Creates new form dietasConsultarDieta
     */
    public dietasConsultarDieta() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDietasConsultarDieta = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanelDietasConsultarDietaLayout = new javax.swing.GroupLayout(jPanelDietasConsultarDieta);
        jPanelDietasConsultarDieta.setLayout(jPanelDietasConsultarDietaLayout);
        jPanelDietasConsultarDietaLayout.setHorizontalGroup(
            jPanelDietasConsultarDietaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1075, Short.MAX_VALUE)
        );
        jPanelDietasConsultarDietaLayout.setVerticalGroup(
            jPanelDietasConsultarDietaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDietasConsultarDieta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDietasConsultarDieta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelDietasConsultarDieta;
    // End of variables declaration//GEN-END:variables
}
